# Generated by Django 5.1 on 2024-08-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='title',
            new_name='name',
        ),
    ]
