# Generated by Django 5.1 on 2024-09-01 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_title_dish_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
